# Generated by Django 6.0.5 on 2026-05-13 12:48

import animals.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
            ],
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер помещения')),
                ('name', models.CharField(max_length=100, verbose_name='Название комплекса')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Наличие водоема')),
                ('area', models.FloatField(verbose_name='Площадь (м2)')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип корма')),
                ('daily_amount', models.FloatField(help_text='кг в сутки', verbose_name='Норма потребления')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='news_pics/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вида')),
                ('animal_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animalclass', verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +375 (29) XXX-XX-XX', regex='^\\+375 \\((29|33|44|25)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('birth_date', models.DateField(validators=[animals.models.validate_age_18], verbose_name='Дата рождения')),
                ('access_card_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.accesscard')),
                ('assigned_enclosure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.enclosure', verbose_name='Закрепленный вольер')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('arrival_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals_pics/', verbose_name='Фото')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animaltype', verbose_name='Вид')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.enclosure', verbose_name='Помещение')),
                ('feeds', models.ManyToManyField(to='animals.feedtype', verbose_name='Рацион')),
            ],
        ),
    ]
