# Generated by Django 6.0.5 on 2026-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animals_photos/', verbose_name='Фотография'),
        ),
    ]
