# Generated by Django 6.0.5 on 2026-05-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
    ]
