# Generated by Django 5.2.4 on 2026-05-15 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_accesscard_id_alter_animal_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscard',
            options={'verbose_name': 'Пропуск', 'verbose_name_plural': 'Пропуски'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterModelOptions(
            name='animalclass',
            options={'verbose_name': 'Класс животных', 'verbose_name_plural': 'Классы животных'},
        ),
        migrations.AlterModelOptions(
            name='animaltype',
            options={'verbose_name': 'Вид животного', 'verbose_name_plural': 'Виды животных'},
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Сообщения обратной связи'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='enclosure',
            options={'verbose_name': 'Вольер', 'verbose_name_plural': 'Вольеры'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AlterModelOptions(
            name='feedtype',
            options={'verbose_name': 'Вид корма', 'verbose_name_plural': 'Виды корма'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_description',
            field=models.TextField(blank=True, verbose_name='Описание выполняемых работ'),
        ),
        migrations.AlterField(
            model_name='accesscard',
            name='card_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='accesscard',
            name='issued_at',
            field=models.DateField(auto_now_add=True, verbose_name='Выдана'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='access_card_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.accesscard', verbose_name='Личный пропуск'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='assigned_enclosure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.enclosure', verbose_name='Закрепленный вольер'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_content',
            field=models.CharField(max_length=255, verbose_name='Краткое содержание (1 предложение)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(verbose_name='Описание акции'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действует (не в архиве)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
