# Generated by Django 5.2.4 on 2026-05-15 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_accesscard_options_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={},
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_percent',
            field=models.IntegerField(default=0, verbose_name='Скидка %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_until',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Годен до'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='posted_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Для чего'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=100, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
    ]
