# Generated by Django 5.2.4 on 2026-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_alter_promocode_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
