# Generated by Django 5.2.4 on 2026-05-19 03:06

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_animal_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Словарь терминов', 'verbose_name_plural': 'Словарь терминов и понятий'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(validators=[animals.models.validate_not_future], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(validators=[animals.models.validate_age_18, animals.models.validate_not_future], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления на сайт'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Определение / Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Термин / Вопрос'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата (локальная)'),
        ),
    ]
