# Generated by Django 5.2.4 on 2026-05-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_alter_faq_options_alter_animal_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
