# Generated by Django 5.2.4 on 2026-05-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_remove_animal_photo_animal_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на картинку'),
        ),
    ]
